# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: free_chips.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='free_chips.proto',
  package='pb',
  syntax='proto2',
  serialized_options=_b('Z\005../pb'),
  serialized_pb=_b('\n\x10\x66ree_chips.proto\x12\x02pb\"+\n\rFreeChipsInfo\x12\r\n\x05\x63hips\x18\x01 \x01(\x03\x12\x0b\n\x03num\x18\x02 \x01(\x05\"\x15\n\x13GetFreeChipsInfoREQ\"m\n\x13GetFreeChipsInfoRSP\x12)\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x1b.pb.GetFreeChipsInfoRSPCode\x12+\n\x10\x66ree_chips_infos\x18\x02 \x03(\x0b\x32\x11.pb.FreeChipsInfo\"\x11\n\x0f\x41\x64\x64\x46reeChipsBRC*j\n\x17GetFreeChipsInfoRSPCode\x12#\n\x1fGetFreeChipsInfoRSPCode_SUCCESS\x10\x00\x12*\n\x1dGetFreeChipsInfoRSPCode_ERROR\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01\x42\x07Z\x05../pb')
)

_GETFREECHIPSINFORSPCODE = _descriptor.EnumDescriptor(
  name='GetFreeChipsInfoRSPCode',
  full_name='pb.GetFreeChipsInfoRSPCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GetFreeChipsInfoRSPCode_SUCCESS', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GetFreeChipsInfoRSPCode_ERROR', index=1, number=-1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=222,
  serialized_end=328,
)
_sym_db.RegisterEnumDescriptor(_GETFREECHIPSINFORSPCODE)

GetFreeChipsInfoRSPCode = enum_type_wrapper.EnumTypeWrapper(_GETFREECHIPSINFORSPCODE)
GetFreeChipsInfoRSPCode_SUCCESS = 0
GetFreeChipsInfoRSPCode_ERROR = -1



_FREECHIPSINFO = _descriptor.Descriptor(
  name='FreeChipsInfo',
  full_name='pb.FreeChipsInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='chips', full_name='pb.FreeChipsInfo.chips', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num', full_name='pb.FreeChipsInfo.num', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=67,
)


_GETFREECHIPSINFOREQ = _descriptor.Descriptor(
  name='GetFreeChipsInfoREQ',
  full_name='pb.GetFreeChipsInfoREQ',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=90,
)


_GETFREECHIPSINFORSP = _descriptor.Descriptor(
  name='GetFreeChipsInfoRSP',
  full_name='pb.GetFreeChipsInfoRSP',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='pb.GetFreeChipsInfoRSP.code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='free_chips_infos', full_name='pb.GetFreeChipsInfoRSP.free_chips_infos', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=201,
)


_ADDFREECHIPSBRC = _descriptor.Descriptor(
  name='AddFreeChipsBRC',
  full_name='pb.AddFreeChipsBRC',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=203,
  serialized_end=220,
)

_GETFREECHIPSINFORSP.fields_by_name['code'].enum_type = _GETFREECHIPSINFORSPCODE
_GETFREECHIPSINFORSP.fields_by_name['free_chips_infos'].message_type = _FREECHIPSINFO
DESCRIPTOR.message_types_by_name['FreeChipsInfo'] = _FREECHIPSINFO
DESCRIPTOR.message_types_by_name['GetFreeChipsInfoREQ'] = _GETFREECHIPSINFOREQ
DESCRIPTOR.message_types_by_name['GetFreeChipsInfoRSP'] = _GETFREECHIPSINFORSP
DESCRIPTOR.message_types_by_name['AddFreeChipsBRC'] = _ADDFREECHIPSBRC
DESCRIPTOR.enum_types_by_name['GetFreeChipsInfoRSPCode'] = _GETFREECHIPSINFORSPCODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FreeChipsInfo = _reflection.GeneratedProtocolMessageType('FreeChipsInfo', (_message.Message,), dict(
  DESCRIPTOR = _FREECHIPSINFO,
  __module__ = 'free_chips_pb2'
  # @@protoc_insertion_point(class_scope:pb.FreeChipsInfo)
  ))
_sym_db.RegisterMessage(FreeChipsInfo)

GetFreeChipsInfoREQ = _reflection.GeneratedProtocolMessageType('GetFreeChipsInfoREQ', (_message.Message,), dict(
  DESCRIPTOR = _GETFREECHIPSINFOREQ,
  __module__ = 'free_chips_pb2'
  # @@protoc_insertion_point(class_scope:pb.GetFreeChipsInfoREQ)
  ))
_sym_db.RegisterMessage(GetFreeChipsInfoREQ)

GetFreeChipsInfoRSP = _reflection.GeneratedProtocolMessageType('GetFreeChipsInfoRSP', (_message.Message,), dict(
  DESCRIPTOR = _GETFREECHIPSINFORSP,
  __module__ = 'free_chips_pb2'
  # @@protoc_insertion_point(class_scope:pb.GetFreeChipsInfoRSP)
  ))
_sym_db.RegisterMessage(GetFreeChipsInfoRSP)

AddFreeChipsBRC = _reflection.GeneratedProtocolMessageType('AddFreeChipsBRC', (_message.Message,), dict(
  DESCRIPTOR = _ADDFREECHIPSBRC,
  __module__ = 'free_chips_pb2'
  # @@protoc_insertion_point(class_scope:pb.AddFreeChipsBRC)
  ))
_sym_db.RegisterMessage(AddFreeChipsBRC)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
