# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cash_storm.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import base2_pb2 as base2__pb2
import pre_base_pb2 as pre__base__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='cash_storm.proto',
  package='pb',
  syntax='proto2',
  serialized_options=_b('Z\005../pb'),
  serialized_pb=_b('\n\x10\x63\x61sh_storm.proto\x12\x02pb\x1a\x0b\x62\x61se2.proto\x1a\x0epre_base.proto\"\xbe\x03\n\x1fiCashStormAccumulateGameTimeREQ\x12\x36\n\x04user\x18\x01 \x03(\x0b\x32(.pb.iCashStormAccumulateGameTimeREQ.User\x12\x13\n\x0bstandup_uid\x18\x02 \x03(\x03\x12\r\n\x05setid\x18\x03 \x01(\t\x12\x0e\n\x06gameid\x18\x04 \x01(\t\x12\x13\n\x0bsmall_blind\x18\x05 \x01(\x03\x12\x17\n\x0fgame_start_time\x18\x06 \x01(\x03\x12\x15\n\rgame_end_time\x18\x07 \x01(\x03\x12\x1f\n\troom_type\x18\x08 \x01(\x0e\x32\x0c.pb.RoomType\x12\x1f\n\tgame_mode\x18\t \x01(\x0e\x32\x0c.pb.GameMode\x12\x10\n\x08\x62omb_pot\x18\n \x01(\x08\x12#\n\x18\x62ombpot_additional_board\x18\x0b \x01(\x05:\x01\x30\x12\x1b\n\x10\x61\x64\x64itional_board\x18\x0c \x01(\x05:\x01\x30\x1aT\n\x04User\x12\x0b\n\x03uid\x18\x01 \x01(\x03\x12\x10\n\x08nickname\x18\x02 \x01(\t\x12\x15\n\rclub_platform\x18\x03 \x03(\t\x12\x16\n\x0ehead_image_url\x18\x04 \x01(\t\"?\n\x1fiCashStormAccumulateGameTimeRSP\x12\x1c\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x0e.pb.iErrorCodeB\x07Z\x05../pb')
  ,
  dependencies=[base2__pb2.DESCRIPTOR,pre__base__pb2.DESCRIPTOR,])




_ICASHSTORMACCUMULATEGAMETIMEREQ_USER = _descriptor.Descriptor(
  name='User',
  full_name='pb.iCashStormAccumulateGameTimeREQ.User',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='pb.iCashStormAccumulateGameTimeREQ.User.uid', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nickname', full_name='pb.iCashStormAccumulateGameTimeREQ.User.nickname', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='club_platform', full_name='pb.iCashStormAccumulateGameTimeREQ.User.club_platform', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='head_image_url', full_name='pb.iCashStormAccumulateGameTimeREQ.User.head_image_url', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=416,
  serialized_end=500,
)

_ICASHSTORMACCUMULATEGAMETIMEREQ = _descriptor.Descriptor(
  name='iCashStormAccumulateGameTimeREQ',
  full_name='pb.iCashStormAccumulateGameTimeREQ',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user', full_name='pb.iCashStormAccumulateGameTimeREQ.user', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='standup_uid', full_name='pb.iCashStormAccumulateGameTimeREQ.standup_uid', index=1,
      number=2, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='setid', full_name='pb.iCashStormAccumulateGameTimeREQ.setid', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gameid', full_name='pb.iCashStormAccumulateGameTimeREQ.gameid', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='small_blind', full_name='pb.iCashStormAccumulateGameTimeREQ.small_blind', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='game_start_time', full_name='pb.iCashStormAccumulateGameTimeREQ.game_start_time', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='game_end_time', full_name='pb.iCashStormAccumulateGameTimeREQ.game_end_time', index=6,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='room_type', full_name='pb.iCashStormAccumulateGameTimeREQ.room_type', index=7,
      number=8, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='game_mode', full_name='pb.iCashStormAccumulateGameTimeREQ.game_mode', index=8,
      number=9, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bomb_pot', full_name='pb.iCashStormAccumulateGameTimeREQ.bomb_pot', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bombpot_additional_board', full_name='pb.iCashStormAccumulateGameTimeREQ.bombpot_additional_board', index=10,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='additional_board', full_name='pb.iCashStormAccumulateGameTimeREQ.additional_board', index=11,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_ICASHSTORMACCUMULATEGAMETIMEREQ_USER, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=500,
)


_ICASHSTORMACCUMULATEGAMETIMERSP = _descriptor.Descriptor(
  name='iCashStormAccumulateGameTimeRSP',
  full_name='pb.iCashStormAccumulateGameTimeRSP',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='pb.iCashStormAccumulateGameTimeRSP.code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=502,
  serialized_end=565,
)

_ICASHSTORMACCUMULATEGAMETIMEREQ_USER.containing_type = _ICASHSTORMACCUMULATEGAMETIMEREQ
_ICASHSTORMACCUMULATEGAMETIMEREQ.fields_by_name['user'].message_type = _ICASHSTORMACCUMULATEGAMETIMEREQ_USER
_ICASHSTORMACCUMULATEGAMETIMEREQ.fields_by_name['room_type'].enum_type = pre__base__pb2._ROOMTYPE
_ICASHSTORMACCUMULATEGAMETIMEREQ.fields_by_name['game_mode'].enum_type = pre__base__pb2._GAMEMODE
_ICASHSTORMACCUMULATEGAMETIMERSP.fields_by_name['code'].enum_type = base2__pb2._IERRORCODE
DESCRIPTOR.message_types_by_name['iCashStormAccumulateGameTimeREQ'] = _ICASHSTORMACCUMULATEGAMETIMEREQ
DESCRIPTOR.message_types_by_name['iCashStormAccumulateGameTimeRSP'] = _ICASHSTORMACCUMULATEGAMETIMERSP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

iCashStormAccumulateGameTimeREQ = _reflection.GeneratedProtocolMessageType('iCashStormAccumulateGameTimeREQ', (_message.Message,), dict(

  User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), dict(
    DESCRIPTOR = _ICASHSTORMACCUMULATEGAMETIMEREQ_USER,
    __module__ = 'cash_storm_pb2'
    # @@protoc_insertion_point(class_scope:pb.iCashStormAccumulateGameTimeREQ.User)
    ))
  ,
  DESCRIPTOR = _ICASHSTORMACCUMULATEGAMETIMEREQ,
  __module__ = 'cash_storm_pb2'
  # @@protoc_insertion_point(class_scope:pb.iCashStormAccumulateGameTimeREQ)
  ))
_sym_db.RegisterMessage(iCashStormAccumulateGameTimeREQ)
_sym_db.RegisterMessage(iCashStormAccumulateGameTimeREQ.User)

iCashStormAccumulateGameTimeRSP = _reflection.GeneratedProtocolMessageType('iCashStormAccumulateGameTimeRSP', (_message.Message,), dict(
  DESCRIPTOR = _ICASHSTORMACCUMULATEGAMETIMERSP,
  __module__ = 'cash_storm_pb2'
  # @@protoc_insertion_point(class_scope:pb.iCashStormAccumulateGameTimeRSP)
  ))
_sym_db.RegisterMessage(iCashStormAccumulateGameTimeRSP)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
