# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inner_bigcache.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='inner_bigcache.proto',
  package='pb',
  syntax='proto2',
  serialized_options=_b('Z\005../pb'),
  serialized_pb=_b('\n\x14inner_bigcache.proto\x12\x02pb\"U\n\rBigCacheEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12\x13\n\x0binsert_time\x18\x03 \x01(\t\x12\x13\n\x0b\x65xpire_time\x18\x04 \x01(\t\">\n\x0c\x42igCacheData\x12\x0c\n\x04name\x18\x01 \x01(\t\x12 \n\x05\x63\x61\x63he\x18\x02 \x03(\x0b\x32\x11.pb.BigCacheEntry\"\"\n\x13iInspectBigCacheREQ\x12\x0b\n\x03key\x18\x01 \x01(\t\"5\n\x13iInspectBigCacheRSP\x12\x1e\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x10.pb.BigCacheDataB\x07Z\x05../pb')
)




_BIGCACHEENTRY = _descriptor.Descriptor(
  name='BigCacheEntry',
  full_name='pb.BigCacheEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='pb.BigCacheEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='pb.BigCacheEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='insert_time', full_name='pb.BigCacheEntry.insert_time', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='expire_time', full_name='pb.BigCacheEntry.expire_time', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=113,
)


_BIGCACHEDATA = _descriptor.Descriptor(
  name='BigCacheData',
  full_name='pb.BigCacheData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='pb.BigCacheData.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cache', full_name='pb.BigCacheData.cache', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=177,
)


_IINSPECTBIGCACHEREQ = _descriptor.Descriptor(
  name='iInspectBigCacheREQ',
  full_name='pb.iInspectBigCacheREQ',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='pb.iInspectBigCacheREQ.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=179,
  serialized_end=213,
)


_IINSPECTBIGCACHERSP = _descriptor.Descriptor(
  name='iInspectBigCacheRSP',
  full_name='pb.iInspectBigCacheRSP',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='pb.iInspectBigCacheRSP.data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=215,
  serialized_end=268,
)

_BIGCACHEDATA.fields_by_name['cache'].message_type = _BIGCACHEENTRY
_IINSPECTBIGCACHERSP.fields_by_name['data'].message_type = _BIGCACHEDATA
DESCRIPTOR.message_types_by_name['BigCacheEntry'] = _BIGCACHEENTRY
DESCRIPTOR.message_types_by_name['BigCacheData'] = _BIGCACHEDATA
DESCRIPTOR.message_types_by_name['iInspectBigCacheREQ'] = _IINSPECTBIGCACHEREQ
DESCRIPTOR.message_types_by_name['iInspectBigCacheRSP'] = _IINSPECTBIGCACHERSP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BigCacheEntry = _reflection.GeneratedProtocolMessageType('BigCacheEntry', (_message.Message,), dict(
  DESCRIPTOR = _BIGCACHEENTRY,
  __module__ = 'inner_bigcache_pb2'
  # @@protoc_insertion_point(class_scope:pb.BigCacheEntry)
  ))
_sym_db.RegisterMessage(BigCacheEntry)

BigCacheData = _reflection.GeneratedProtocolMessageType('BigCacheData', (_message.Message,), dict(
  DESCRIPTOR = _BIGCACHEDATA,
  __module__ = 'inner_bigcache_pb2'
  # @@protoc_insertion_point(class_scope:pb.BigCacheData)
  ))
_sym_db.RegisterMessage(BigCacheData)

iInspectBigCacheREQ = _reflection.GeneratedProtocolMessageType('iInspectBigCacheREQ', (_message.Message,), dict(
  DESCRIPTOR = _IINSPECTBIGCACHEREQ,
  __module__ = 'inner_bigcache_pb2'
  # @@protoc_insertion_point(class_scope:pb.iInspectBigCacheREQ)
  ))
_sym_db.RegisterMessage(iInspectBigCacheREQ)

iInspectBigCacheRSP = _reflection.GeneratedProtocolMessageType('iInspectBigCacheRSP', (_message.Message,), dict(
  DESCRIPTOR = _IINSPECTBIGCACHERSP,
  __module__ = 'inner_bigcache_pb2'
  # @@protoc_insertion_point(class_scope:pb.iInspectBigCacheRSP)
  ))
_sym_db.RegisterMessage(iInspectBigCacheRSP)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
