import sys
import os

sys.path.append(os.path.abspath(os.path.dirname(__file__)))

from achievement_base_pb2 import *
from achievement_pb2 import *
from activity3_pb2 import *
from activity_base_pb2 import *
from activity_pb2 import *
from aof_treasure_pb2 import *
from base2_pb2 import *
from base_pb2 import *
from blind_coin_pb2 import *
from calltime_pb2 import *
from career_pb2 import *
from cashier_pb2 import *
from cash_back_pb2 import *
from cash_storm_pb2 import *
from cheers_activity_pb2 import *
from club1_pb2 import *
from club2_pb2 import *
from club3_pb2 import *
from club4_pb2 import *
from club_base_pb2 import *
from club_helper_pb2 import *
from common_pb2 import *
from counter_pb2 import *
from deposit_activity_pb2 import *
from free_chips_pb2 import *
from frozen_value_pb2 import *
from game_record_producer_pb2 import *
from gift_code_pb2 import *
from go_club_pb2 import *
from go_game_gateway_pb2 import *
from go_mission_pb2 import *
from go_roomrouter_pb2 import *
from go_user_pb2 import *
from grpc_pb2 import *
from halloween_2023_pb2 import *
from hands_review_pb2 import *
from inner_achievement_pb2 import *
from inner_aof_treasure_pb2 import *
from inner_base_pb2 import *
from inner_cash_back_pb2 import *
from inner_deposit_activity_pb2 import *
from inner_go_room_list_pb2 import *
from inner_go_room_pb2 import *
from inner_go_user_pb2 import *
from inner_item_pb2 import *
from inner_jackpot_pb2 import *
from inner_new_comers_guide_pb2 import *
from inner_pb2 import *
from inner_push_center_pb2 import *
from inner_shop_pb2 import *
from invite_pb2 import *
from item_pb2 import *
from jackpot_pb2 import *
from kyc_pb2 import *
from leaderboard_activity_base_pb2 import *
from leaderboard_activity_pb2 import *
from league_pb2 import *
from lucky_draw_base_pb2 import *
from lucky_draw_pb2 import *
from mission_base_pb2 import *
from mission_pb2 import *
from monitor_verify_kyc_pb2 import *
from mtt1_pb2 import *
from mtt2_pb2 import *
from mtt_pb2 import *
from new_comers_guide_pb2 import *
from pb1_pb2 import *
from pb2_pb2 import *
from pb3_pb2 import *
from pb4_pb2 import *
from pb5_pb2 import *
from pb6_pb2 import *
from pb7_pb2 import *
from pine1_pb2 import *
from pine_pb2 import *
from pppoker_pb2 import *
from pre_base_pb2 import *
from push_center_pb2 import *
from rebate_base_pb2 import *
from rebate_pb2 import *
from risk_management_pb2 import *
from roomrouter_pb2 import *
from room_pb2 import *
from shared_pb2 import *
from shark_king_flip_pb2 import *
from shop_item_list_pb2 import *
from shop_pb2 import *
from sng_pb2 import *
from ticket_pb2 import *
from translation_pb2 import *
from trophy_base_pb2 import *
from trophy_pb2 import *
from user_relation_pb2 import *
from user_setting_pb2 import *
from value_pb2 import *
from vip_pb2 import *
from watchdog_pb2 import *
from __init__ import *
