# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cashier.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import base2_pb2 as base2__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='cashier.proto',
  package='pb',
  syntax='proto2',
  serialized_options=_b('Z\005../pb'),
  serialized_pb=_b('\n\rcashier.proto\x12\x02pb\x1a\x0b\x62\x61se2.proto\"H\n\x1fiSetCounterWithdrawBlacklistREQ\x12\x0b\n\x03uid\x18\x01 \x01(\x03\x12\x18\n\x10is_ban_by_button\x18\x02 \x01(\x08\"O\n\x1fiSetCounterWithdrawBlacklistRSP\x12\x1c\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x0e.pb.iErrorCode\x12\x0e\n\x06reason\x18\x02 \x01(\tB\x07Z\x05../pb')
  ,
  dependencies=[base2__pb2.DESCRIPTOR,])




_ISETCOUNTERWITHDRAWBLACKLISTREQ = _descriptor.Descriptor(
  name='iSetCounterWithdrawBlacklistREQ',
  full_name='pb.iSetCounterWithdrawBlacklistREQ',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='pb.iSetCounterWithdrawBlacklistREQ.uid', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_ban_by_button', full_name='pb.iSetCounterWithdrawBlacklistREQ.is_ban_by_button', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=106,
)


_ISETCOUNTERWITHDRAWBLACKLISTRSP = _descriptor.Descriptor(
  name='iSetCounterWithdrawBlacklistRSP',
  full_name='pb.iSetCounterWithdrawBlacklistRSP',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='pb.iSetCounterWithdrawBlacklistRSP.code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reason', full_name='pb.iSetCounterWithdrawBlacklistRSP.reason', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=108,
  serialized_end=187,
)

_ISETCOUNTERWITHDRAWBLACKLISTRSP.fields_by_name['code'].enum_type = base2__pb2._IERRORCODE
DESCRIPTOR.message_types_by_name['iSetCounterWithdrawBlacklistREQ'] = _ISETCOUNTERWITHDRAWBLACKLISTREQ
DESCRIPTOR.message_types_by_name['iSetCounterWithdrawBlacklistRSP'] = _ISETCOUNTERWITHDRAWBLACKLISTRSP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

iSetCounterWithdrawBlacklistREQ = _reflection.GeneratedProtocolMessageType('iSetCounterWithdrawBlacklistREQ', (_message.Message,), dict(
  DESCRIPTOR = _ISETCOUNTERWITHDRAWBLACKLISTREQ,
  __module__ = 'cashier_pb2'
  # @@protoc_insertion_point(class_scope:pb.iSetCounterWithdrawBlacklistREQ)
  ))
_sym_db.RegisterMessage(iSetCounterWithdrawBlacklistREQ)

iSetCounterWithdrawBlacklistRSP = _reflection.GeneratedProtocolMessageType('iSetCounterWithdrawBlacklistRSP', (_message.Message,), dict(
  DESCRIPTOR = _ISETCOUNTERWITHDRAWBLACKLISTRSP,
  __module__ = 'cashier_pb2'
  # @@protoc_insertion_point(class_scope:pb.iSetCounterWithdrawBlacklistRSP)
  ))
_sym_db.RegisterMessage(iSetCounterWithdrawBlacklistRSP)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
