# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inner_cash_back.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import base2_pb2 as base2__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='inner_cash_back.proto',
  package='pb',
  syntax='proto2',
  serialized_options=_b('Z\005../pb'),
  serialized_pb=_b('\n\x15inner_cash_back.proto\x12\x02pb\x1a\x0b\x62\x61se2.proto\"+\n\x1ciBanUserAutoClaimCashbackREQ\x12\x0b\n\x03uid\x18\x01 \x01(\x03\"<\n\x1ciBanUserAutoClaimCashbackRSP\x12\x1c\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x0e.pb.iErrorCodeB\x07Z\x05../pb')
  ,
  dependencies=[base2__pb2.DESCRIPTOR,])




_IBANUSERAUTOCLAIMCASHBACKREQ = _descriptor.Descriptor(
  name='iBanUserAutoClaimCashbackREQ',
  full_name='pb.iBanUserAutoClaimCashbackREQ',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='pb.iBanUserAutoClaimCashbackREQ.uid', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=85,
)


_IBANUSERAUTOCLAIMCASHBACKRSP = _descriptor.Descriptor(
  name='iBanUserAutoClaimCashbackRSP',
  full_name='pb.iBanUserAutoClaimCashbackRSP',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='pb.iBanUserAutoClaimCashbackRSP.code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=147,
)

_IBANUSERAUTOCLAIMCASHBACKRSP.fields_by_name['code'].enum_type = base2__pb2._IERRORCODE
DESCRIPTOR.message_types_by_name['iBanUserAutoClaimCashbackREQ'] = _IBANUSERAUTOCLAIMCASHBACKREQ
DESCRIPTOR.message_types_by_name['iBanUserAutoClaimCashbackRSP'] = _IBANUSERAUTOCLAIMCASHBACKRSP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

iBanUserAutoClaimCashbackREQ = _reflection.GeneratedProtocolMessageType('iBanUserAutoClaimCashbackREQ', (_message.Message,), dict(
  DESCRIPTOR = _IBANUSERAUTOCLAIMCASHBACKREQ,
  __module__ = 'inner_cash_back_pb2'
  # @@protoc_insertion_point(class_scope:pb.iBanUserAutoClaimCashbackREQ)
  ))
_sym_db.RegisterMessage(iBanUserAutoClaimCashbackREQ)

iBanUserAutoClaimCashbackRSP = _reflection.GeneratedProtocolMessageType('iBanUserAutoClaimCashbackRSP', (_message.Message,), dict(
  DESCRIPTOR = _IBANUSERAUTOCLAIMCASHBACKRSP,
  __module__ = 'inner_cash_back_pb2'
  # @@protoc_insertion_point(class_scope:pb.iBanUserAutoClaimCashbackRSP)
  ))
_sym_db.RegisterMessage(iBanUserAutoClaimCashbackRSP)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
