# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inner_go_club.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import base2_pb2 as base2__pb2
import club4_pb2 as club4__pb2
import inner_pb2 as inner__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='inner_go_club.proto',
  package='pb',
  syntax='proto2',
  serialized_options=_b('Z\005../pb'),
  serialized_pb=_b('\n\x13inner_go_club.proto\x12\x02pb\x1a\x0b\x62\x61se2.proto\x1a\x0b\x63lub4.proto\x1a\x0binner.proto\"+\n\x1ciBanUserAutoClaimRakebackREQ\x12\x0b\n\x03uid\x18\x01 \x02(\x03\"<\n\x1ciBanUserAutoClaimRakebackRSP\x12\x1c\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x0e.pb.iErrorCode\" \n\x11iGetClubListV2REQ\x12\x0b\n\x03uid\x18\x01 \x01(\x03\"V\n\x11iGetClubListV2RSP\x12%\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x0e.pb.iErrorCode:\x07SUCCESS\x12\x1a\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32\x0c.pb.ClubInfo\"\xb3\x01\n\x12RestrictedPlatform\x12\x10\n\x08platform\x18\x01 \x01(\t\x12\x0f\n\x07\x63lub_id\x18\x02 \x01(\x05\x12&\n\x0c\x63ontact_info\x18\x03 \x03(\x0b\x32\x10.pb.MultiLangMsg\x12\x12\n\nbegin_time\x18\x04 \x01(\x03\x12\x10\n\x08\x65nd_time\x18\x05 \x01(\x03\x12\x0c\n\x04type\x18\x06 \x01(\x05\x12\x0f\n\x07\x63lubids\x18\x07 \x01(\t\x12\r\n\x05state\x18\x08 \x01(\t\"{\n\x1ciUpdateRestrictedPlatformREQ\x12$\n\x04info\x18\x01 \x01(\x0b\x32\x16.pb.RestrictedPlatform\x12\x35\n\x0bupdate_type\x18\x02 \x01(\x0e\x32 .pb.UpdateRestrictedPlatformType\"U\n\x1ciUpdateRestrictedPlatformRSP\x12%\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x0e.pb.iErrorCode:\x07SUCCESS\x12\x0e\n\x06reason\x18\x02 \x01(\t\"\x1b\n\x19iGetRestrictedPlatformREQ\"h\n\x19iGetRestrictedPlatformRSP\x12%\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x0e.pb.iErrorCode:\x07SUCCESS\x12$\n\x04info\x18\x02 \x03(\x0b\x32\x16.pb.RestrictedPlatform\"1\n\x0eiCreateClubREQ\x12\x0b\n\x03uid\x18\x01 \x01(\x03\x12\x12\n\nutc_offset\x18\x02 \x01(\t\".\n\x0eiCreateClubRSP\x12\x1c\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x0e.pb.iErrorCode*X\n\x1cUpdateRestrictedPlatformType\x12\x0e\n\nCREATE_NEW\x10\x01\x12\x13\n\x0fUPDATE_EXISTING\x10\x02\x12\x13\n\x0f\x43\x41NCEL_EXISTING\x10\x03\x42\x07Z\x05../pb')
  ,
  dependencies=[base2__pb2.DESCRIPTOR,club4__pb2.DESCRIPTOR,inner__pb2.DESCRIPTOR,])

_UPDATERESTRICTEDPLATFORMTYPE = _descriptor.EnumDescriptor(
  name='UpdateRestrictedPlatformType',
  full_name='pb.UpdateRestrictedPlatformType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CREATE_NEW', index=0, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UPDATE_EXISTING', index=1, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CANCEL_EXISTING', index=2, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=923,
  serialized_end=1011,
)
_sym_db.RegisterEnumDescriptor(_UPDATERESTRICTEDPLATFORMTYPE)

UpdateRestrictedPlatformType = enum_type_wrapper.EnumTypeWrapper(_UPDATERESTRICTEDPLATFORMTYPE)
CREATE_NEW = 1
UPDATE_EXISTING = 2
CANCEL_EXISTING = 3



_IBANUSERAUTOCLAIMRAKEBACKREQ = _descriptor.Descriptor(
  name='iBanUserAutoClaimRakebackREQ',
  full_name='pb.iBanUserAutoClaimRakebackREQ',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='pb.iBanUserAutoClaimRakebackREQ.uid', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=109,
)


_IBANUSERAUTOCLAIMRAKEBACKRSP = _descriptor.Descriptor(
  name='iBanUserAutoClaimRakebackRSP',
  full_name='pb.iBanUserAutoClaimRakebackRSP',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='pb.iBanUserAutoClaimRakebackRSP.code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=171,
)


_IGETCLUBLISTV2REQ = _descriptor.Descriptor(
  name='iGetClubListV2REQ',
  full_name='pb.iGetClubListV2REQ',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='pb.iGetClubListV2REQ.uid', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=173,
  serialized_end=205,
)


_IGETCLUBLISTV2RSP = _descriptor.Descriptor(
  name='iGetClubListV2RSP',
  full_name='pb.iGetClubListV2RSP',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='pb.iGetClubListV2RSP.code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='pb.iGetClubListV2RSP.data', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=207,
  serialized_end=293,
)


_RESTRICTEDPLATFORM = _descriptor.Descriptor(
  name='RestrictedPlatform',
  full_name='pb.RestrictedPlatform',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='platform', full_name='pb.RestrictedPlatform.platform', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='club_id', full_name='pb.RestrictedPlatform.club_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='contact_info', full_name='pb.RestrictedPlatform.contact_info', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='begin_time', full_name='pb.RestrictedPlatform.begin_time', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end_time', full_name='pb.RestrictedPlatform.end_time', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='pb.RestrictedPlatform.type', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='clubids', full_name='pb.RestrictedPlatform.clubids', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='state', full_name='pb.RestrictedPlatform.state', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=296,
  serialized_end=475,
)


_IUPDATERESTRICTEDPLATFORMREQ = _descriptor.Descriptor(
  name='iUpdateRestrictedPlatformREQ',
  full_name='pb.iUpdateRestrictedPlatformREQ',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='info', full_name='pb.iUpdateRestrictedPlatformREQ.info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='update_type', full_name='pb.iUpdateRestrictedPlatformREQ.update_type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=477,
  serialized_end=600,
)


_IUPDATERESTRICTEDPLATFORMRSP = _descriptor.Descriptor(
  name='iUpdateRestrictedPlatformRSP',
  full_name='pb.iUpdateRestrictedPlatformRSP',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='pb.iUpdateRestrictedPlatformRSP.code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reason', full_name='pb.iUpdateRestrictedPlatformRSP.reason', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=602,
  serialized_end=687,
)


_IGETRESTRICTEDPLATFORMREQ = _descriptor.Descriptor(
  name='iGetRestrictedPlatformREQ',
  full_name='pb.iGetRestrictedPlatformREQ',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=689,
  serialized_end=716,
)


_IGETRESTRICTEDPLATFORMRSP = _descriptor.Descriptor(
  name='iGetRestrictedPlatformRSP',
  full_name='pb.iGetRestrictedPlatformRSP',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='pb.iGetRestrictedPlatformRSP.code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='info', full_name='pb.iGetRestrictedPlatformRSP.info', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=718,
  serialized_end=822,
)


_ICREATECLUBREQ = _descriptor.Descriptor(
  name='iCreateClubREQ',
  full_name='pb.iCreateClubREQ',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='pb.iCreateClubREQ.uid', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='utc_offset', full_name='pb.iCreateClubREQ.utc_offset', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=824,
  serialized_end=873,
)


_ICREATECLUBRSP = _descriptor.Descriptor(
  name='iCreateClubRSP',
  full_name='pb.iCreateClubRSP',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='pb.iCreateClubRSP.code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=875,
  serialized_end=921,
)

_IBANUSERAUTOCLAIMRAKEBACKRSP.fields_by_name['code'].enum_type = base2__pb2._IERRORCODE
_IGETCLUBLISTV2RSP.fields_by_name['code'].enum_type = base2__pb2._IERRORCODE
_IGETCLUBLISTV2RSP.fields_by_name['data'].message_type = club4__pb2._CLUBINFO
_RESTRICTEDPLATFORM.fields_by_name['contact_info'].message_type = inner__pb2._MULTILANGMSG
_IUPDATERESTRICTEDPLATFORMREQ.fields_by_name['info'].message_type = _RESTRICTEDPLATFORM
_IUPDATERESTRICTEDPLATFORMREQ.fields_by_name['update_type'].enum_type = _UPDATERESTRICTEDPLATFORMTYPE
_IUPDATERESTRICTEDPLATFORMRSP.fields_by_name['code'].enum_type = base2__pb2._IERRORCODE
_IGETRESTRICTEDPLATFORMRSP.fields_by_name['code'].enum_type = base2__pb2._IERRORCODE
_IGETRESTRICTEDPLATFORMRSP.fields_by_name['info'].message_type = _RESTRICTEDPLATFORM
_ICREATECLUBRSP.fields_by_name['code'].enum_type = base2__pb2._IERRORCODE
DESCRIPTOR.message_types_by_name['iBanUserAutoClaimRakebackREQ'] = _IBANUSERAUTOCLAIMRAKEBACKREQ
DESCRIPTOR.message_types_by_name['iBanUserAutoClaimRakebackRSP'] = _IBANUSERAUTOCLAIMRAKEBACKRSP
DESCRIPTOR.message_types_by_name['iGetClubListV2REQ'] = _IGETCLUBLISTV2REQ
DESCRIPTOR.message_types_by_name['iGetClubListV2RSP'] = _IGETCLUBLISTV2RSP
DESCRIPTOR.message_types_by_name['RestrictedPlatform'] = _RESTRICTEDPLATFORM
DESCRIPTOR.message_types_by_name['iUpdateRestrictedPlatformREQ'] = _IUPDATERESTRICTEDPLATFORMREQ
DESCRIPTOR.message_types_by_name['iUpdateRestrictedPlatformRSP'] = _IUPDATERESTRICTEDPLATFORMRSP
DESCRIPTOR.message_types_by_name['iGetRestrictedPlatformREQ'] = _IGETRESTRICTEDPLATFORMREQ
DESCRIPTOR.message_types_by_name['iGetRestrictedPlatformRSP'] = _IGETRESTRICTEDPLATFORMRSP
DESCRIPTOR.message_types_by_name['iCreateClubREQ'] = _ICREATECLUBREQ
DESCRIPTOR.message_types_by_name['iCreateClubRSP'] = _ICREATECLUBRSP
DESCRIPTOR.enum_types_by_name['UpdateRestrictedPlatformType'] = _UPDATERESTRICTEDPLATFORMTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

iBanUserAutoClaimRakebackREQ = _reflection.GeneratedProtocolMessageType('iBanUserAutoClaimRakebackREQ', (_message.Message,), dict(
  DESCRIPTOR = _IBANUSERAUTOCLAIMRAKEBACKREQ,
  __module__ = 'inner_go_club_pb2'
  # @@protoc_insertion_point(class_scope:pb.iBanUserAutoClaimRakebackREQ)
  ))
_sym_db.RegisterMessage(iBanUserAutoClaimRakebackREQ)

iBanUserAutoClaimRakebackRSP = _reflection.GeneratedProtocolMessageType('iBanUserAutoClaimRakebackRSP', (_message.Message,), dict(
  DESCRIPTOR = _IBANUSERAUTOCLAIMRAKEBACKRSP,
  __module__ = 'inner_go_club_pb2'
  # @@protoc_insertion_point(class_scope:pb.iBanUserAutoClaimRakebackRSP)
  ))
_sym_db.RegisterMessage(iBanUserAutoClaimRakebackRSP)

iGetClubListV2REQ = _reflection.GeneratedProtocolMessageType('iGetClubListV2REQ', (_message.Message,), dict(
  DESCRIPTOR = _IGETCLUBLISTV2REQ,
  __module__ = 'inner_go_club_pb2'
  # @@protoc_insertion_point(class_scope:pb.iGetClubListV2REQ)
  ))
_sym_db.RegisterMessage(iGetClubListV2REQ)

iGetClubListV2RSP = _reflection.GeneratedProtocolMessageType('iGetClubListV2RSP', (_message.Message,), dict(
  DESCRIPTOR = _IGETCLUBLISTV2RSP,
  __module__ = 'inner_go_club_pb2'
  # @@protoc_insertion_point(class_scope:pb.iGetClubListV2RSP)
  ))
_sym_db.RegisterMessage(iGetClubListV2RSP)

RestrictedPlatform = _reflection.GeneratedProtocolMessageType('RestrictedPlatform', (_message.Message,), dict(
  DESCRIPTOR = _RESTRICTEDPLATFORM,
  __module__ = 'inner_go_club_pb2'
  # @@protoc_insertion_point(class_scope:pb.RestrictedPlatform)
  ))
_sym_db.RegisterMessage(RestrictedPlatform)

iUpdateRestrictedPlatformREQ = _reflection.GeneratedProtocolMessageType('iUpdateRestrictedPlatformREQ', (_message.Message,), dict(
  DESCRIPTOR = _IUPDATERESTRICTEDPLATFORMREQ,
  __module__ = 'inner_go_club_pb2'
  # @@protoc_insertion_point(class_scope:pb.iUpdateRestrictedPlatformREQ)
  ))
_sym_db.RegisterMessage(iUpdateRestrictedPlatformREQ)

iUpdateRestrictedPlatformRSP = _reflection.GeneratedProtocolMessageType('iUpdateRestrictedPlatformRSP', (_message.Message,), dict(
  DESCRIPTOR = _IUPDATERESTRICTEDPLATFORMRSP,
  __module__ = 'inner_go_club_pb2'
  # @@protoc_insertion_point(class_scope:pb.iUpdateRestrictedPlatformRSP)
  ))
_sym_db.RegisterMessage(iUpdateRestrictedPlatformRSP)

iGetRestrictedPlatformREQ = _reflection.GeneratedProtocolMessageType('iGetRestrictedPlatformREQ', (_message.Message,), dict(
  DESCRIPTOR = _IGETRESTRICTEDPLATFORMREQ,
  __module__ = 'inner_go_club_pb2'
  # @@protoc_insertion_point(class_scope:pb.iGetRestrictedPlatformREQ)
  ))
_sym_db.RegisterMessage(iGetRestrictedPlatformREQ)

iGetRestrictedPlatformRSP = _reflection.GeneratedProtocolMessageType('iGetRestrictedPlatformRSP', (_message.Message,), dict(
  DESCRIPTOR = _IGETRESTRICTEDPLATFORMRSP,
  __module__ = 'inner_go_club_pb2'
  # @@protoc_insertion_point(class_scope:pb.iGetRestrictedPlatformRSP)
  ))
_sym_db.RegisterMessage(iGetRestrictedPlatformRSP)

iCreateClubREQ = _reflection.GeneratedProtocolMessageType('iCreateClubREQ', (_message.Message,), dict(
  DESCRIPTOR = _ICREATECLUBREQ,
  __module__ = 'inner_go_club_pb2'
  # @@protoc_insertion_point(class_scope:pb.iCreateClubREQ)
  ))
_sym_db.RegisterMessage(iCreateClubREQ)

iCreateClubRSP = _reflection.GeneratedProtocolMessageType('iCreateClubRSP', (_message.Message,), dict(
  DESCRIPTOR = _ICREATECLUBRSP,
  __module__ = 'inner_go_club_pb2'
  # @@protoc_insertion_point(class_scope:pb.iCreateClubRSP)
  ))
_sym_db.RegisterMessage(iCreateClubRSP)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
